# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ruby on Rails vs Me
email: congdacit@gmail.com
description:  # this means to ignore newlines until "baseurl:"
  Blog này sẽ chia sẽ những vấn đề về Ruby on Rails trong quá trình mình học, sẽ bắt 
  đầu từ những cái cơ bản , ở đây mình chỉ mới bắt đầu , thế nên đương nhiên những bài viết bắt đầu  
  cũng sẽ chỉ giúp ích cho những người mới bắt đầu =))
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
twitter_username: nguyendac8  

gems: [jekyll-paginate]
paginate: 3
permaling: /:title
# github_username:  NOT

# Build settings
markdown: kramdown
theme: minima
